import StyleDictionary from 'style-dictionary'

// ---------------------------------------------------------------------------
// Custom format: CSS custom properties with dual-theme output
//
// Light tokens (everything except color-dark-*) → :root {}
// Dark tokens  (color-dark-*) → [data-theme="dark"] {} with prefix stripped
// This matches the existing colors.css structure and the data-theme JS trigger.
// ---------------------------------------------------------------------------
StyleDictionary.registerFormat({
  name: 'css/themed',
  format({ dictionary, file }) {
    const header = [
      '/*',
      ' * Sistema — Design Tokens (generated by Style Dictionary)',
      ' * Source: tokens/semantic/ — do not edit this file directly.',
      ' * Regenerate: npm run tokens',
      ' */',
      '',
    ]

    const lightTokens = dictionary.allTokens.filter(
      t => !(t.path[0] === 'color' && t.path[1]?.startsWith('dark-'))
    )
    const darkTokens = dictionary.allTokens.filter(
      t => t.path[0] === 'color' && t.path[1]?.startsWith('dark-')
    )

    const toVar = (token, stripDark = false) => {
      const name = stripDark
        ? token.name.replace(/^color-dark-/, 'color-')
        : token.name
      return `  --${name}: ${token.value};`
    }

    const lightBlock = [':root {', ...lightTokens.map(t => toVar(t)), '}']

    const darkBlock = darkTokens.length > 0
      ? ['', '[data-theme="dark"] {', ...darkTokens.map(t => toVar(t, true)), '}']
      : []

    return [...header, ...lightBlock, ...darkBlock, ''].join('\n')
  },
})

// ---------------------------------------------------------------------------
// Custom format: ESM module
// Named exports — camelCase from the kebab token name.
// Dark tokens exported as colorDark* for completeness (useful in JS theming).
// ---------------------------------------------------------------------------
StyleDictionary.registerFormat({
  name: 'javascript/esm',
  format({ dictionary }) {
    const toCamel = str => str.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase())

    const lines = [
      '// Sistema — Design Tokens (generated by Style Dictionary)',
      '// Source: tokens/semantic/ — do not edit this file directly.',
      '// Regenerate: npm run tokens',
      '',
      ...dictionary.allTokens.map(
        t => `export const ${toCamel(t.name)} = ${JSON.stringify(t.value)};`
      ),
    ]

    return lines.join('\n') + '\n'
  },
})

// ---------------------------------------------------------------------------
// Custom transform group: CSS without px→rem conversion
// The built-in 'css' group converts px values to rem via 'size/rem'.
// This system uses authored rem values in typography and px in shape tokens —
// both intentional. Skipping size/rem preserves the authored values.
// ---------------------------------------------------------------------------
StyleDictionary.registerTransformGroup({
  name: 'css/no-rem',
  transforms: ['attribute/cti', 'name/kebab', 'color/css'],
})

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------
const sd = new StyleDictionary({
  // Primitive files: loaded for reference resolution, NOT included in output.
  // Semantic tokens reference palette values with {palette.blue-brand} notation.
  include: [
    'tokens/primitive/**/*.json',
  ],

  // Semantic files: these become the output tokens.
  source: [
    'tokens/semantic/**/*.json',
  ],

  platforms: {
    css: {
      transformGroup: 'css/no-rem',
      buildPath: 'src/styles/tokens/',
      files: [
        {
          destination: 'generated.css',
          format: 'css/themed',
          // Exclude primitive palette tokens — they live in include[], not source[]
          // but SD v5 outputs them anyway; filter them explicitly here.
          filter: token => token.path[0] !== 'palette',
        },
      ],
    },

    js: {
      transformGroup: 'js',
      buildPath: 'src/styles/tokens/',
      files: [
        {
          destination: 'tokens.mjs',
          format: 'javascript/esm',
          filter: token => token.path[0] !== 'palette',
        },
      ],
    },
  },
})

await sd.buildAllPlatforms()
