/**
 * Do not edit directly, this file was auto-generated.
 */

export default {
  color: {
    "dark-surface": {
      key: "{color.dark-surface}",
      value: "#111111",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.dark-base}",
        key: "{color.dark-surface}",
      },
      name: "ColorDarkSurface",
      attributes: {
        category: "color",
        type: "dark-surface",
      },
      path: ["color", "dark-surface"],
    },
    "dark-surface-raised": {
      key: "{color.dark-surface-raised}",
      value: "#1C1C1C",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.dark-raised}",
        key: "{color.dark-surface-raised}",
      },
      name: "ColorDarkSurfaceRaised",
      attributes: {
        category: "color",
        type: "dark-surface-raised",
      },
      path: ["color", "dark-surface-raised"],
    },
    "dark-surface-overlay": {
      key: "{color.dark-surface-overlay}",
      value: "#252525",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.dark-overlay}",
        key: "{color.dark-surface-overlay}",
      },
      name: "ColorDarkSurfaceOverlay",
      attributes: {
        category: "color",
        type: "dark-surface-overlay",
      },
      path: ["color", "dark-surface-overlay"],
    },
    "dark-on-surface": {
      key: "{color.dark-on-surface}",
      value: "#F3F4F6",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.dark-text}",
        key: "{color.dark-on-surface}",
      },
      name: "ColorDarkOnSurface",
      attributes: {
        category: "color",
        type: "dark-on-surface",
      },
      path: ["color", "dark-on-surface"],
    },
    "dark-on-surface-muted": {
      key: "{color.dark-on-surface-muted}",
      value: "#9CA3AF",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.dark-text-muted}",
        key: "{color.dark-on-surface-muted}",
      },
      name: "ColorDarkOnSurfaceMuted",
      attributes: {
        category: "color",
        type: "dark-on-surface-muted",
      },
      path: ["color", "dark-on-surface-muted"],
    },
    "dark-border": {
      key: "{color.dark-border}",
      value: "#2D2D2D",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.dark-border}",
        key: "{color.dark-border}",
      },
      name: "ColorDarkBorder",
      attributes: {
        category: "color",
        type: "dark-border",
      },
      path: ["color", "dark-border"],
    },
    "dark-border-focus": {
      key: "{color.dark-border-focus}",
      value: "#4D9FFF",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.blue-lifted}",
        key: "{color.dark-border-focus}",
      },
      name: "ColorDarkBorderFocus",
      attributes: {
        category: "color",
        type: "dark-border-focus",
      },
      path: ["color", "dark-border-focus"],
    },
    "dark-primary": {
      key: "{color.dark-primary}",
      value: "#4D9FFF",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.blue-lifted}",
        key: "{color.dark-primary}",
      },
      name: "ColorDarkPrimary",
      attributes: {
        category: "color",
        type: "dark-primary",
      },
      path: ["color", "dark-primary"],
    },
    "dark-on-primary": {
      key: "{color.dark-on-primary}",
      value: "#002D6E",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.blue-darkest}",
        key: "{color.dark-on-primary}",
      },
      name: "ColorDarkOnPrimary",
      attributes: {
        category: "color",
        type: "dark-on-primary",
      },
      path: ["color", "dark-on-primary"],
    },
    "dark-primary-container": {
      key: "{color.dark-primary-container}",
      value: "#1E3A5F",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.blue-container-dark}",
        key: "{color.dark-primary-container}",
      },
      name: "ColorDarkPrimaryContainer",
      attributes: {
        category: "color",
        type: "dark-primary-container",
      },
      path: ["color", "dark-primary-container"],
    },
    "dark-on-primary-container": {
      key: "{color.dark-on-primary-container}",
      value: "#BAD4FF",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.blue-on-container-dark}",
        key: "{color.dark-on-primary-container}",
      },
      name: "ColorDarkOnPrimaryContainer",
      attributes: {
        category: "color",
        type: "dark-on-primary-container",
      },
      path: ["color", "dark-on-primary-container"],
    },
    "dark-secondary": {
      key: "{color.dark-secondary}",
      value: "#FFCC33",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.yellow-brand}",
        key: "{color.dark-secondary}",
      },
      name: "ColorDarkSecondary",
      attributes: {
        category: "color",
        type: "dark-secondary",
      },
      path: ["color", "dark-secondary"],
    },
    "dark-on-secondary": {
      key: "{color.dark-on-secondary}",
      value: "#1A1200",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.yellow-on}",
        key: "{color.dark-on-secondary}",
      },
      name: "ColorDarkOnSecondary",
      attributes: {
        category: "color",
        type: "dark-on-secondary",
      },
      path: ["color", "dark-on-secondary"],
    },
    "dark-secondary-container": {
      key: "{color.dark-secondary-container}",
      value: "#3D2E00",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.yellow-container-dark}",
        key: "{color.dark-secondary-container}",
      },
      name: "ColorDarkSecondaryContainer",
      attributes: {
        category: "color",
        type: "dark-secondary-container",
      },
      path: ["color", "dark-secondary-container"],
    },
    "dark-on-secondary-container": {
      key: "{color.dark-on-secondary-container}",
      value: "#FFCC33",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.yellow-brand}",
        key: "{color.dark-on-secondary-container}",
      },
      name: "ColorDarkOnSecondaryContainer",
      attributes: {
        category: "color",
        type: "dark-on-secondary-container",
      },
      path: ["color", "dark-on-secondary-container"],
    },
    "dark-error": {
      key: "{color.dark-error}",
      value: "#FCA5A5",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.error-dark}",
        key: "{color.dark-error}",
      },
      name: "ColorDarkError",
      attributes: {
        category: "color",
        type: "dark-error",
      },
      path: ["color", "dark-error"],
    },
    "dark-on-error": {
      key: "{color.dark-on-error}",
      value: "#450A0A",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.error-on-dark}",
        key: "{color.dark-on-error}",
      },
      name: "ColorDarkOnError",
      attributes: {
        category: "color",
        type: "dark-on-error",
      },
      path: ["color", "dark-on-error"],
    },
    "dark-success": {
      key: "{color.dark-success}",
      value: "#4ADE80",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.success-dark}",
        key: "{color.dark-success}",
      },
      name: "ColorDarkSuccess",
      attributes: {
        category: "color",
        type: "dark-success",
      },
      path: ["color", "dark-success"],
    },
    "dark-on-success": {
      key: "{color.dark-on-success}",
      value: "#052E16",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.success-on-dark}",
        key: "{color.dark-on-success}",
      },
      name: "ColorDarkOnSuccess",
      attributes: {
        category: "color",
        type: "dark-on-success",
      },
      path: ["color", "dark-on-success"],
    },
    "dark-warning": {
      key: "{color.dark-warning}",
      value: "#FCD34D",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.warning-dark}",
        key: "{color.dark-warning}",
      },
      name: "ColorDarkWarning",
      attributes: {
        category: "color",
        type: "dark-warning",
      },
      path: ["color", "dark-warning"],
    },
    "dark-on-warning": {
      key: "{color.dark-on-warning}",
      value: "#311700",
      filePath: "tokens/semantic/color.dark.json",
      isSource: true,
      original: {
        value: "{palette.warning-on-dark}",
        key: "{color.dark-on-warning}",
      },
      name: "ColorDarkOnWarning",
      attributes: {
        category: "color",
        type: "dark-on-warning",
      },
      path: ["color", "dark-on-warning"],
    },
    canvas: {
      key: "{color.canvas}",
      value: "#FFFFFF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.canvas}",
        key: "{color.canvas}",
      },
      name: "ColorCanvas",
      attributes: {
        category: "color",
        type: "canvas",
      },
      path: ["color", "canvas"],
    },
    surface: {
      key: "{color.surface}",
      value: "#FFFFFF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.surface}",
        key: "{color.surface}",
      },
      name: "ColorSurface",
      attributes: {
        category: "color",
        type: "surface",
      },
      path: ["color", "surface"],
    },
    "surface-raised": {
      key: "{color.surface-raised}",
      value: "#FFFFFF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.white}",
        key: "{color.surface-raised}",
      },
      name: "ColorSurfaceRaised",
      attributes: {
        category: "color",
        type: "surface-raised",
      },
      path: ["color", "surface-raised"],
    },
    "surface-overlay": {
      key: "{color.surface-overlay}",
      value: "#FFFFFF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.white}",
        key: "{color.surface-overlay}",
      },
      name: "ColorSurfaceOverlay",
      attributes: {
        category: "color",
        type: "surface-overlay",
      },
      path: ["color", "surface-overlay"],
    },
    "surface-sunken": {
      key: "{color.surface-sunken}",
      value: "#F7F6F2",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.surface-sunken}",
        key: "{color.surface-sunken}",
      },
      name: "ColorSurfaceSunken",
      attributes: {
        category: "color",
        type: "surface-sunken",
      },
      path: ["color", "surface-sunken"],
    },
    "on-surface": {
      key: "{color.on-surface}",
      value: "#0E1116",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.text}",
        key: "{color.on-surface}",
      },
      name: "ColorOnSurface",
      attributes: {
        category: "color",
        type: "on-surface",
      },
      path: ["color", "on-surface"],
    },
    "on-surface-muted": {
      key: "{color.on-surface-muted}",
      value: "#5B6470",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.text-muted}",
        key: "{color.on-surface-muted}",
      },
      name: "ColorOnSurfaceMuted",
      attributes: {
        category: "color",
        type: "on-surface-muted",
      },
      path: ["color", "on-surface-muted"],
    },
    "on-surface-subtle": {
      key: "{color.on-surface-subtle}",
      value: "#8A929C",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.text-subtle}",
        key: "{color.on-surface-subtle}",
      },
      name: "ColorOnSurfaceSubtle",
      attributes: {
        category: "color",
        type: "on-surface-subtle",
      },
      path: ["color", "on-surface-subtle"],
    },
    border: {
      key: "{color.border}",
      value: "#E4E7EB",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.border}",
        key: "{color.border}",
      },
      name: "ColorBorder",
      attributes: {
        category: "color",
        type: "border",
      },
      path: ["color", "border"],
    },
    "border-strong": {
      key: "{color.border-strong}",
      value: "#C9CFD6",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.border-strong}",
        key: "{color.border-strong}",
      },
      name: "ColorBorderStrong",
      attributes: {
        category: "color",
        type: "border-strong",
      },
      path: ["color", "border-strong"],
    },
    "border-focus": {
      key: "{color.border-focus}",
      value: "#0070FF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.blue-brand}",
        key: "{color.border-focus}",
      },
      name: "ColorBorderFocus",
      attributes: {
        category: "color",
        type: "border-focus",
      },
      path: ["color", "border-focus"],
    },
    "brand-yellow": {
      key: "{color.brand-yellow}",
      value: "#FFCC33",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.yellow-brand}",
        key: "{color.brand-yellow}",
      },
      name: "ColorBrandYellow",
      attributes: {
        category: "color",
        type: "brand-yellow",
      },
      path: ["color", "brand-yellow"],
    },
    "brand-yellow-50": {
      key: "{color.brand-yellow-50}",
      value: "#FFF8E0",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.yellow-50}",
        key: "{color.brand-yellow-50}",
      },
      name: "ColorBrandYellow50",
      attributes: {
        category: "color",
        type: "brand-yellow-50",
      },
      path: ["color", "brand-yellow-50"],
    },
    "brand-red": {
      key: "{color.brand-red}",
      value: "#E60026",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.brand-red}",
        key: "{color.brand-red}",
      },
      name: "ColorBrandRed",
      attributes: {
        category: "color",
        type: "brand-red",
      },
      path: ["color", "brand-red"],
    },
    "brand-blue-50": {
      key: "{color.brand-blue-50}",
      value: "#E6F0FF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.blue-50}",
        key: "{color.brand-blue-50}",
      },
      name: "ColorBrandBlue50",
      attributes: {
        category: "color",
        type: "brand-blue-50",
      },
      path: ["color", "brand-blue-50"],
    },
    primary: {
      key: "{color.primary}",
      value: "#0070FF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.blue-brand}",
        key: "{color.primary}",
      },
      name: "ColorPrimary",
      attributes: {
        category: "color",
        type: "primary",
      },
      path: ["color", "primary"],
    },
    "on-primary": {
      key: "{color.on-primary}",
      value: "#FFFFFF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.white}",
        key: "{color.on-primary}",
      },
      name: "ColorOnPrimary",
      attributes: {
        category: "color",
        type: "on-primary",
      },
      path: ["color", "on-primary"],
    },
    "primary-container": {
      key: "{color.primary-container}",
      value: "#E8F1FF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.blue-container}",
        key: "{color.primary-container}",
      },
      name: "ColorPrimaryContainer",
      attributes: {
        category: "color",
        type: "primary-container",
      },
      path: ["color", "primary-container"],
    },
    "on-primary-container": {
      key: "{color.on-primary-container}",
      value: "#003A9E",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.blue-deep}",
        key: "{color.on-primary-container}",
      },
      name: "ColorOnPrimaryContainer",
      attributes: {
        category: "color",
        type: "on-primary-container",
      },
      path: ["color", "on-primary-container"],
    },
    secondary: {
      key: "{color.secondary}",
      value: "#FFCC33",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.yellow-brand}",
        key: "{color.secondary}",
      },
      name: "ColorSecondary",
      attributes: {
        category: "color",
        type: "secondary",
      },
      path: ["color", "secondary"],
    },
    "on-secondary": {
      key: "{color.on-secondary}",
      value: "#1A1200",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.yellow-on}",
        key: "{color.on-secondary}",
      },
      name: "ColorOnSecondary",
      attributes: {
        category: "color",
        type: "on-secondary",
      },
      path: ["color", "on-secondary"],
    },
    "secondary-container": {
      key: "{color.secondary-container}",
      value: "#FFF9E6",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.yellow-container}",
        key: "{color.secondary-container}",
      },
      name: "ColorSecondaryContainer",
      attributes: {
        category: "color",
        type: "secondary-container",
      },
      path: ["color", "secondary-container"],
    },
    "on-secondary-container": {
      key: "{color.on-secondary-container}",
      value: "#4A3800",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.yellow-on-container}",
        key: "{color.on-secondary-container}",
      },
      name: "ColorOnSecondaryContainer",
      attributes: {
        category: "color",
        type: "on-secondary-container",
      },
      path: ["color", "on-secondary-container"],
    },
    error: {
      key: "{color.error}",
      value: "#B91C1C",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.error}",
        key: "{color.error}",
      },
      name: "ColorError",
      attributes: {
        category: "color",
        type: "error",
      },
      path: ["color", "error"],
    },
    "on-error": {
      key: "{color.on-error}",
      value: "#FFFFFF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.white}",
        key: "{color.on-error}",
      },
      name: "ColorOnError",
      attributes: {
        category: "color",
        type: "on-error",
      },
      path: ["color", "on-error"],
    },
    success: {
      key: "{color.success}",
      value: "#15803D",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.success}",
        key: "{color.success}",
      },
      name: "ColorSuccess",
      attributes: {
        category: "color",
        type: "success",
      },
      path: ["color", "success"],
    },
    "on-success": {
      key: "{color.on-success}",
      value: "#FFFFFF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.white}",
        key: "{color.on-success}",
      },
      name: "ColorOnSuccess",
      attributes: {
        category: "color",
        type: "on-success",
      },
      path: ["color", "on-success"],
    },
    warning: {
      key: "{color.warning}",
      value: "#B45309",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.warning}",
        key: "{color.warning}",
      },
      name: "ColorWarning",
      attributes: {
        category: "color",
        type: "warning",
      },
      path: ["color", "warning"],
    },
    "on-warning": {
      key: "{color.on-warning}",
      value: "#FFFFFF",
      filePath: "tokens/semantic/color.json",
      isSource: true,
      original: {
        value: "{palette.white}",
        key: "{color.on-warning}",
      },
      name: "ColorOnWarning",
      attributes: {
        category: "color",
        type: "on-warning",
      },
      path: ["color", "on-warning"],
    },
  },
  radius: {
    none: {
      key: "{radius.none}",
      value: "0px",
      filePath: "tokens/semantic/shape.json",
      isSource: true,
      original: {
        value: "0px",
        key: "{radius.none}",
      },
      name: "RadiusNone",
      attributes: {
        category: "radius",
        type: "none",
      },
      path: ["radius", "none"],
    },
    sm: {
      key: "{radius.sm}",
      value: "6px",
      filePath: "tokens/semantic/shape.json",
      isSource: true,
      original: {
        value: "6px",
        key: "{radius.sm}",
      },
      name: "RadiusSm",
      attributes: {
        category: "radius",
        type: "sm",
      },
      path: ["radius", "sm"],
    },
    md: {
      key: "{radius.md}",
      value: "10px",
      filePath: "tokens/semantic/shape.json",
      isSource: true,
      original: {
        value: "10px",
        key: "{radius.md}",
      },
      name: "RadiusMd",
      attributes: {
        category: "radius",
        type: "md",
      },
      path: ["radius", "md"],
    },
    lg: {
      key: "{radius.lg}",
      value: "16px",
      filePath: "tokens/semantic/shape.json",
      isSource: true,
      original: {
        value: "16px",
        key: "{radius.lg}",
      },
      name: "RadiusLg",
      attributes: {
        category: "radius",
        type: "lg",
      },
      path: ["radius", "lg"],
    },
    xl: {
      key: "{radius.xl}",
      value: "22px",
      filePath: "tokens/semantic/shape.json",
      isSource: true,
      original: {
        value: "22px",
        key: "{radius.xl}",
      },
      name: "RadiusXl",
      attributes: {
        category: "radius",
        type: "xl",
      },
      path: ["radius", "xl"],
    },
    full: {
      key: "{radius.full}",
      value: "9999px",
      filePath: "tokens/semantic/shape.json",
      isSource: true,
      original: {
        value: "9999px",
        key: "{radius.full}",
      },
      name: "RadiusFull",
      attributes: {
        category: "radius",
        type: "full",
      },
      path: ["radius", "full"],
    },
  },
  shadow: {
    sm: {
      key: "{shadow.sm}",
      value: "0 1px 2px rgba(14,17,22,0.05)",
      filePath: "tokens/semantic/shape.json",
      isSource: true,
      original: {
        value: "0 1px 2px rgba(14,17,22,0.05)",
        key: "{shadow.sm}",
      },
      name: "ShadowSm",
      attributes: {
        category: "shadow",
        type: "sm",
      },
      path: ["shadow", "sm"],
    },
    md: {
      key: "{shadow.md}",
      value: "0 4px 14px rgba(14,17,22,0.06), 0 1px 2px rgba(14,17,22,0.04)",
      filePath: "tokens/semantic/shape.json",
      isSource: true,
      original: {
        value: "0 4px 14px rgba(14,17,22,0.06), 0 1px 2px rgba(14,17,22,0.04)",
        key: "{shadow.md}",
      },
      name: "ShadowMd",
      attributes: {
        category: "shadow",
        type: "md",
      },
      path: ["shadow", "md"],
    },
  },
  font: {
    sans: {
      key: "{font.sans}",
      value: "'Inter', system-ui, -apple-system, sans-serif",
      filePath: "tokens/semantic/typography.json",
      isSource: true,
      original: {
        value: "'Inter', system-ui, -apple-system, sans-serif",
        key: "{font.sans}",
      },
      name: "FontSans",
      attributes: {
        category: "font",
        type: "sans",
      },
      path: ["font", "sans"],
    },
    serif: {
      key: "{font.serif}",
      value: "'Fraunces', Georgia, 'Times New Roman', serif",
      filePath: "tokens/semantic/typography.json",
      isSource: true,
      original: {
        value: "'Fraunces', Georgia, 'Times New Roman', serif",
        key: "{font.serif}",
      },
      name: "FontSerif",
      attributes: {
        category: "font",
        type: "serif",
      },
      path: ["font", "serif"],
    },
    mono: {
      key: "{font.mono}",
      value: "'JetBrains Mono', 'Cascadia Code', 'Fira Mono', monospace",
      filePath: "tokens/semantic/typography.json",
      isSource: true,
      original: {
        value: "'JetBrains Mono', 'Cascadia Code', 'Fira Mono', monospace",
        key: "{font.mono}",
      },
      name: "FontMono",
      attributes: {
        category: "font",
        type: "mono",
      },
      path: ["font", "mono"],
    },
  },
  type: {
    display: {
      font: {
        key: "{type.display.font}",
        value: "var(--font-sans)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-sans)",
          key: "{type.display.font}",
        },
        name: "TypeDisplayFont",
        attributes: {
          category: "type",
          type: "display",
          item: "font",
        },
        path: ["type", "display", "font"],
      },
      size: {
        key: "{type.display.size}",
        value: "3.5rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "3.5rem",
          key: "{type.display.size}",
        },
        name: "TypeDisplaySize",
        attributes: {
          category: "type",
          type: "display",
          item: "size",
        },
        path: ["type", "display", "size"],
      },
      weight: {
        key: "{type.display.weight}",
        value: 800,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 800,
          key: "{type.display.weight}",
        },
        name: "TypeDisplayWeight",
        attributes: {
          category: "type",
          type: "display",
          item: "weight",
        },
        path: ["type", "display", "weight"],
      },
      "line-height": {
        key: "{type.display.line-height}",
        value: 1,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1,
          key: "{type.display.line-height}",
        },
        name: "TypeDisplayLineHeight",
        attributes: {
          category: "type",
          type: "display",
          item: "line-height",
        },
        path: ["type", "display", "line-height"],
      },
      "letter-spacing": {
        key: "{type.display.letter-spacing}",
        value: "-0.025em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "-0.025em",
          key: "{type.display.letter-spacing}",
        },
        name: "TypeDisplayLetterSpacing",
        attributes: {
          category: "type",
          type: "display",
          item: "letter-spacing",
        },
        path: ["type", "display", "letter-spacing"],
      },
    },
    "heading-xl": {
      font: {
        key: "{type.heading-xl.font}",
        value: "var(--font-sans)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-sans)",
          key: "{type.heading-xl.font}",
        },
        name: "TypeHeadingXlFont",
        attributes: {
          category: "type",
          type: "heading-xl",
          item: "font",
        },
        path: ["type", "heading-xl", "font"],
      },
      size: {
        key: "{type.heading-xl.size}",
        value: "2.5rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "2.5rem",
          key: "{type.heading-xl.size}",
        },
        name: "TypeHeadingXlSize",
        attributes: {
          category: "type",
          type: "heading-xl",
          item: "size",
        },
        path: ["type", "heading-xl", "size"],
      },
      weight: {
        key: "{type.heading-xl.weight}",
        value: 700,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 700,
          key: "{type.heading-xl.weight}",
        },
        name: "TypeHeadingXlWeight",
        attributes: {
          category: "type",
          type: "heading-xl",
          item: "weight",
        },
        path: ["type", "heading-xl", "weight"],
      },
      "line-height": {
        key: "{type.heading-xl.line-height}",
        value: 1.1,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.1,
          key: "{type.heading-xl.line-height}",
        },
        name: "TypeHeadingXlLineHeight",
        attributes: {
          category: "type",
          type: "heading-xl",
          item: "line-height",
        },
        path: ["type", "heading-xl", "line-height"],
      },
      "letter-spacing": {
        key: "{type.heading-xl.letter-spacing}",
        value: "-0.02em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "-0.02em",
          key: "{type.heading-xl.letter-spacing}",
        },
        name: "TypeHeadingXlLetterSpacing",
        attributes: {
          category: "type",
          type: "heading-xl",
          item: "letter-spacing",
        },
        path: ["type", "heading-xl", "letter-spacing"],
      },
    },
    "heading-lg": {
      font: {
        key: "{type.heading-lg.font}",
        value: "var(--font-sans)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-sans)",
          key: "{type.heading-lg.font}",
        },
        name: "TypeHeadingLgFont",
        attributes: {
          category: "type",
          type: "heading-lg",
          item: "font",
        },
        path: ["type", "heading-lg", "font"],
      },
      size: {
        key: "{type.heading-lg.size}",
        value: "2rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "2rem",
          key: "{type.heading-lg.size}",
        },
        name: "TypeHeadingLgSize",
        attributes: {
          category: "type",
          type: "heading-lg",
          item: "size",
        },
        path: ["type", "heading-lg", "size"],
      },
      weight: {
        key: "{type.heading-lg.weight}",
        value: 700,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 700,
          key: "{type.heading-lg.weight}",
        },
        name: "TypeHeadingLgWeight",
        attributes: {
          category: "type",
          type: "heading-lg",
          item: "weight",
        },
        path: ["type", "heading-lg", "weight"],
      },
      "line-height": {
        key: "{type.heading-lg.line-height}",
        value: 1.15,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.15,
          key: "{type.heading-lg.line-height}",
        },
        name: "TypeHeadingLgLineHeight",
        attributes: {
          category: "type",
          type: "heading-lg",
          item: "line-height",
        },
        path: ["type", "heading-lg", "line-height"],
      },
      "letter-spacing": {
        key: "{type.heading-lg.letter-spacing}",
        value: "-0.015em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "-0.015em",
          key: "{type.heading-lg.letter-spacing}",
        },
        name: "TypeHeadingLgLetterSpacing",
        attributes: {
          category: "type",
          type: "heading-lg",
          item: "letter-spacing",
        },
        path: ["type", "heading-lg", "letter-spacing"],
      },
    },
    "heading-md": {
      font: {
        key: "{type.heading-md.font}",
        value: "var(--font-sans)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-sans)",
          key: "{type.heading-md.font}",
        },
        name: "TypeHeadingMdFont",
        attributes: {
          category: "type",
          type: "heading-md",
          item: "font",
        },
        path: ["type", "heading-md", "font"],
      },
      size: {
        key: "{type.heading-md.size}",
        value: "1.5rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "1.5rem",
          key: "{type.heading-md.size}",
        },
        name: "TypeHeadingMdSize",
        attributes: {
          category: "type",
          type: "heading-md",
          item: "size",
        },
        path: ["type", "heading-md", "size"],
      },
      weight: {
        key: "{type.heading-md.weight}",
        value: 600,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 600,
          key: "{type.heading-md.weight}",
        },
        name: "TypeHeadingMdWeight",
        attributes: {
          category: "type",
          type: "heading-md",
          item: "weight",
        },
        path: ["type", "heading-md", "weight"],
      },
      "line-height": {
        key: "{type.heading-md.line-height}",
        value: 1.2,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.2,
          key: "{type.heading-md.line-height}",
        },
        name: "TypeHeadingMdLineHeight",
        attributes: {
          category: "type",
          type: "heading-md",
          item: "line-height",
        },
        path: ["type", "heading-md", "line-height"],
      },
      "letter-spacing": {
        key: "{type.heading-md.letter-spacing}",
        value: "-0.01em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "-0.01em",
          key: "{type.heading-md.letter-spacing}",
        },
        name: "TypeHeadingMdLetterSpacing",
        attributes: {
          category: "type",
          type: "heading-md",
          item: "letter-spacing",
        },
        path: ["type", "heading-md", "letter-spacing"],
      },
    },
    "heading-sm": {
      font: {
        key: "{type.heading-sm.font}",
        value: "var(--font-sans)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-sans)",
          key: "{type.heading-sm.font}",
        },
        name: "TypeHeadingSmFont",
        attributes: {
          category: "type",
          type: "heading-sm",
          item: "font",
        },
        path: ["type", "heading-sm", "font"],
      },
      size: {
        key: "{type.heading-sm.size}",
        value: "1.25rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "1.25rem",
          key: "{type.heading-sm.size}",
        },
        name: "TypeHeadingSmSize",
        attributes: {
          category: "type",
          type: "heading-sm",
          item: "size",
        },
        path: ["type", "heading-sm", "size"],
      },
      weight: {
        key: "{type.heading-sm.weight}",
        value: 600,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 600,
          key: "{type.heading-sm.weight}",
        },
        name: "TypeHeadingSmWeight",
        attributes: {
          category: "type",
          type: "heading-sm",
          item: "weight",
        },
        path: ["type", "heading-sm", "weight"],
      },
      "line-height": {
        key: "{type.heading-sm.line-height}",
        value: 1.3,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.3,
          key: "{type.heading-sm.line-height}",
        },
        name: "TypeHeadingSmLineHeight",
        attributes: {
          category: "type",
          type: "heading-sm",
          item: "line-height",
        },
        path: ["type", "heading-sm", "line-height"],
      },
      "letter-spacing": {
        key: "{type.heading-sm.letter-spacing}",
        value: "0em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0em",
          key: "{type.heading-sm.letter-spacing}",
        },
        name: "TypeHeadingSmLetterSpacing",
        attributes: {
          category: "type",
          type: "heading-sm",
          item: "letter-spacing",
        },
        path: ["type", "heading-sm", "letter-spacing"],
      },
    },
    "body-lg": {
      font: {
        key: "{type.body-lg.font}",
        value: "var(--font-serif)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-serif)",
          key: "{type.body-lg.font}",
        },
        name: "TypeBodyLgFont",
        attributes: {
          category: "type",
          type: "body-lg",
          item: "font",
        },
        path: ["type", "body-lg", "font"],
      },
      size: {
        key: "{type.body-lg.size}",
        value: "1.125rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "1.125rem",
          key: "{type.body-lg.size}",
        },
        name: "TypeBodyLgSize",
        attributes: {
          category: "type",
          type: "body-lg",
          item: "size",
        },
        path: ["type", "body-lg", "size"],
      },
      weight: {
        key: "{type.body-lg.weight}",
        value: 400,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 400,
          key: "{type.body-lg.weight}",
        },
        name: "TypeBodyLgWeight",
        attributes: {
          category: "type",
          type: "body-lg",
          item: "weight",
        },
        path: ["type", "body-lg", "weight"],
      },
      "line-height": {
        key: "{type.body-lg.line-height}",
        value: 1.75,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.75,
          key: "{type.body-lg.line-height}",
        },
        name: "TypeBodyLgLineHeight",
        attributes: {
          category: "type",
          type: "body-lg",
          item: "line-height",
        },
        path: ["type", "body-lg", "line-height"],
      },
      "letter-spacing": {
        key: "{type.body-lg.letter-spacing}",
        value: "0em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0em",
          key: "{type.body-lg.letter-spacing}",
        },
        name: "TypeBodyLgLetterSpacing",
        attributes: {
          category: "type",
          type: "body-lg",
          item: "letter-spacing",
        },
        path: ["type", "body-lg", "letter-spacing"],
      },
    },
    "body-md": {
      font: {
        key: "{type.body-md.font}",
        value: "var(--font-serif)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-serif)",
          key: "{type.body-md.font}",
        },
        name: "TypeBodyMdFont",
        attributes: {
          category: "type",
          type: "body-md",
          item: "font",
        },
        path: ["type", "body-md", "font"],
      },
      size: {
        key: "{type.body-md.size}",
        value: "1rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "1rem",
          key: "{type.body-md.size}",
        },
        name: "TypeBodyMdSize",
        attributes: {
          category: "type",
          type: "body-md",
          item: "size",
        },
        path: ["type", "body-md", "size"],
      },
      weight: {
        key: "{type.body-md.weight}",
        value: 400,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 400,
          key: "{type.body-md.weight}",
        },
        name: "TypeBodyMdWeight",
        attributes: {
          category: "type",
          type: "body-md",
          item: "weight",
        },
        path: ["type", "body-md", "weight"],
      },
      "line-height": {
        key: "{type.body-md.line-height}",
        value: 1.65,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.65,
          key: "{type.body-md.line-height}",
        },
        name: "TypeBodyMdLineHeight",
        attributes: {
          category: "type",
          type: "body-md",
          item: "line-height",
        },
        path: ["type", "body-md", "line-height"],
      },
      "letter-spacing": {
        key: "{type.body-md.letter-spacing}",
        value: "0em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0em",
          key: "{type.body-md.letter-spacing}",
        },
        name: "TypeBodyMdLetterSpacing",
        attributes: {
          category: "type",
          type: "body-md",
          item: "letter-spacing",
        },
        path: ["type", "body-md", "letter-spacing"],
      },
    },
    "body-sm": {
      font: {
        key: "{type.body-sm.font}",
        value: "var(--font-serif)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-serif)",
          key: "{type.body-sm.font}",
        },
        name: "TypeBodySmFont",
        attributes: {
          category: "type",
          type: "body-sm",
          item: "font",
        },
        path: ["type", "body-sm", "font"],
      },
      size: {
        key: "{type.body-sm.size}",
        value: "0.875rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0.875rem",
          key: "{type.body-sm.size}",
        },
        name: "TypeBodySmSize",
        attributes: {
          category: "type",
          type: "body-sm",
          item: "size",
        },
        path: ["type", "body-sm", "size"],
      },
      weight: {
        key: "{type.body-sm.weight}",
        value: 400,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 400,
          key: "{type.body-sm.weight}",
        },
        name: "TypeBodySmWeight",
        attributes: {
          category: "type",
          type: "body-sm",
          item: "weight",
        },
        path: ["type", "body-sm", "weight"],
      },
      "line-height": {
        key: "{type.body-sm.line-height}",
        value: 1.6,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.6,
          key: "{type.body-sm.line-height}",
        },
        name: "TypeBodySmLineHeight",
        attributes: {
          category: "type",
          type: "body-sm",
          item: "line-height",
        },
        path: ["type", "body-sm", "line-height"],
      },
      "letter-spacing": {
        key: "{type.body-sm.letter-spacing}",
        value: "0.005em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0.005em",
          key: "{type.body-sm.letter-spacing}",
        },
        name: "TypeBodySmLetterSpacing",
        attributes: {
          category: "type",
          type: "body-sm",
          item: "letter-spacing",
        },
        path: ["type", "body-sm", "letter-spacing"],
      },
    },
    label: {
      font: {
        key: "{type.label.font}",
        value: "var(--font-sans)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-sans)",
          key: "{type.label.font}",
        },
        name: "TypeLabelFont",
        attributes: {
          category: "type",
          type: "label",
          item: "font",
        },
        path: ["type", "label", "font"],
      },
      size: {
        key: "{type.label.size}",
        value: "0.75rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0.75rem",
          key: "{type.label.size}",
        },
        name: "TypeLabelSize",
        attributes: {
          category: "type",
          type: "label",
          item: "size",
        },
        path: ["type", "label", "size"],
      },
      weight: {
        key: "{type.label.weight}",
        value: 500,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 500,
          key: "{type.label.weight}",
        },
        name: "TypeLabelWeight",
        attributes: {
          category: "type",
          type: "label",
          item: "weight",
        },
        path: ["type", "label", "weight"],
      },
      "line-height": {
        key: "{type.label.line-height}",
        value: 1.35,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.35,
          key: "{type.label.line-height}",
        },
        name: "TypeLabelLineHeight",
        attributes: {
          category: "type",
          type: "label",
          item: "line-height",
        },
        path: ["type", "label", "line-height"],
      },
      "letter-spacing": {
        key: "{type.label.letter-spacing}",
        value: "0.02em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0.02em",
          key: "{type.label.letter-spacing}",
        },
        name: "TypeLabelLetterSpacing",
        attributes: {
          category: "type",
          type: "label",
          item: "letter-spacing",
        },
        path: ["type", "label", "letter-spacing"],
      },
    },
    caption: {
      font: {
        key: "{type.caption.font}",
        value: "var(--font-sans)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-sans)",
          key: "{type.caption.font}",
        },
        name: "TypeCaptionFont",
        attributes: {
          category: "type",
          type: "caption",
          item: "font",
        },
        path: ["type", "caption", "font"],
      },
      size: {
        key: "{type.caption.size}",
        value: "0.6875rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0.6875rem",
          key: "{type.caption.size}",
        },
        name: "TypeCaptionSize",
        attributes: {
          category: "type",
          type: "caption",
          item: "size",
        },
        path: ["type", "caption", "size"],
      },
      weight: {
        key: "{type.caption.weight}",
        value: 400,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 400,
          key: "{type.caption.weight}",
        },
        name: "TypeCaptionWeight",
        attributes: {
          category: "type",
          type: "caption",
          item: "weight",
        },
        path: ["type", "caption", "weight"],
      },
      "line-height": {
        key: "{type.caption.line-height}",
        value: 1.4,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.4,
          key: "{type.caption.line-height}",
        },
        name: "TypeCaptionLineHeight",
        attributes: {
          category: "type",
          type: "caption",
          item: "line-height",
        },
        path: ["type", "caption", "line-height"],
      },
      "letter-spacing": {
        key: "{type.caption.letter-spacing}",
        value: "0.025em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0.025em",
          key: "{type.caption.letter-spacing}",
        },
        name: "TypeCaptionLetterSpacing",
        attributes: {
          category: "type",
          type: "caption",
          item: "letter-spacing",
        },
        path: ["type", "caption", "letter-spacing"],
      },
    },
    code: {
      font: {
        key: "{type.code.font}",
        value: "var(--font-mono)",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "var(--font-mono)",
          key: "{type.code.font}",
        },
        name: "TypeCodeFont",
        attributes: {
          category: "type",
          type: "code",
          item: "font",
        },
        path: ["type", "code", "font"],
      },
      size: {
        key: "{type.code.size}",
        value: "0.875rem",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0.875rem",
          key: "{type.code.size}",
        },
        name: "TypeCodeSize",
        attributes: {
          category: "type",
          type: "code",
          item: "size",
        },
        path: ["type", "code", "size"],
      },
      weight: {
        key: "{type.code.weight}",
        value: 400,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 400,
          key: "{type.code.weight}",
        },
        name: "TypeCodeWeight",
        attributes: {
          category: "type",
          type: "code",
          item: "weight",
        },
        path: ["type", "code", "weight"],
      },
      "line-height": {
        key: "{type.code.line-height}",
        value: 1.7,
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: 1.7,
          key: "{type.code.line-height}",
        },
        name: "TypeCodeLineHeight",
        attributes: {
          category: "type",
          type: "code",
          item: "line-height",
        },
        path: ["type", "code", "line-height"],
      },
      "letter-spacing": {
        key: "{type.code.letter-spacing}",
        value: "0em",
        filePath: "tokens/semantic/typography.json",
        isSource: true,
        original: {
          value: "0em",
          key: "{type.code.letter-spacing}",
        },
        name: "TypeCodeLetterSpacing",
        attributes: {
          category: "type",
          type: "code",
          item: "letter-spacing",
        },
        path: ["type", "code", "letter-spacing"],
      },
    },
  },
};
